<!DOCTYPE html>
<html lang="ru" dir="ltr">

<head>
    <base href=""/>
    <title>Triangle Web</title>
    <meta charset="utf-8"/>

    <!-- About App -->
    <meta name="title" content="Triangle Web"/>
    <meta name="description" content=""/>
    <meta name="keywords" content=""/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>

    <meta name="language" content="RU"/>
    <meta name="robots" content="noindex,nofollow"/>

    <!-- About System -->
    <meta name="application-name" content="Triangle Web">
    <meta name="generator" content="Triangle Framework">

    <!-- SEO -->
    <link rel="icon" type="image/svg+xml" href="https://cdn.localzet.com/assets/media/localzet.svg"/>

    <meta name="color-scheme" content="dark light">
    <meta name="theme-color" media="(prefers-color-scheme: dark)" content="#121212">
    <meta name="theme-color" media="(prefers-color-scheme: light)" content="#ffffff">

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="stylesheet" type="text/css"
          href="https://fonts.googleapis.com/css2?family=Nunito:wght@300;400;500;600;700&display=swap"/>

    <style>
        body {
            background-color: #000;
            font-family: Nunito, monospace;
            font-weight: 600;
            text-align: center;
            display: flex;
            flex-direction: column;
            height: 100vh;
            margin: 0;
            overflow: hidden;
        }

        main {
            display: flex;
            flex-direction: column;
            justify-content: space-around;
            align-items: center;
            overflow-y: auto;
            flex-grow: 1;
        }

        main img {
            display: block;
            -webkit-user-select: none;
            transition: background-color 300ms;
        }

        main h1 {
            text-align: start;
            font-size: 1.6rem;
            word-wrap: break-word;
            max-width: 90vw;
            width: fit-content;
        }

        footer {
            width: 100%;
            margin-bottom: 5px;
        }

        footer nav {
            display: flex;
            justify-content: space-between;
            text-align: center;
            margin: 0 10px;
        }

        footer nav a {
            text-decoration: none !important;
            color: #6e7681;
            margin: 0 3px;
            display: inline-block;
        }

        footer nav a b {
            color: #50cd89;
        }

        hr {
            border-color: #50cd89;
            border-radius: 50%;
            width: 100%;
        }

        @media (max-width: 900px) {
            main img {
                margin: auto 5%;
                width: 80%;
                height: auto;
            }
        }
    </style>
</head>

<body>
<main>
    <?php use localzet\Server;

    $print = $error ?? $data ?? 'Ошибка'; ?>
    <h1>
        <pre><?= is_string($print) ? $print : json($print) ?></pre>
    </h1>
</main>
<footer>
    <hr>
    <nav>
        <a target="_blank" href="https://github.com/Triangle-org">Copyright © 2018-<?= date('Y') ?> <b>Triangle Team</b></a>
        <a target="_blank" href="https://github.com/localzet/server">Powered by <b>Localzet
                Server <?= @Server::getVersion() ?? '' ?></b></a>
    </nav>
</footer>
</body>

</html>